### ISSUE TITLE
Operation ERGPKVOperationCanReceiveInvoice hat keine out-Parameter

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/spec-E-Rechnung#17]
Die Operation ERGPKVOperationCanReceiveInvoice hat zwar ein definiertes outputProfile, aber keine Parameter mit type = #out.

Ist das erlaubt?

**Comment by simoneOnFhir** [comment]
Definition der in-Parameter passt auch nicht zu dem input-Profile

#displayname vs. #name

**Comment by alexzautke** [comment]
Ist im aktuellen Arbeitsstand behoben.
