### ISSUE TITLE
$submit-Operation sollte TokenPDF zurückgeben statt Link

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/spec-E-Rechnung#18]
Die Operation sollte einen Output vom Type Resource statt Reference zurückgeben.

An sonsten macht es keinen Sinn, dass wir die Rückgabe des PDFs mit einem boolean-Parameter steuern. Dann könnte ja der Client selbst entscheiden, ob er das PDF abrufen möchte, oder nicht.

Also entweder geben wir nur einen Link zurück und überlassen es dem Client, diesen abzurufen oder wir geben die Binary-Ressource zurück und machen es über einen Parameter steuerbar.

So wie es jetzt ist, macht es aus meiner Sicht keinen Sinn...

**Comment by alexzautke** [comment]
Ist angepasst im aktuellen Arbeitstand
